### ISSUE TITLE
ICSD: Bug because of changed year

### ISSUE THREAD

**Issue by TimoSommer** [simonverret/materials_data_api_scripts#1]
Hi,

thanks for these scripts, they're really great! I found one bug in the download file for the ICSD. After downloading the data, the text is split into a list of cifs. The separator there contains the currrent year, which has changed since you uploaded this, therefore it doesn't work atm. I propose to use the datetime library to make the year always the current year.

**Comment by 279zlj** [comment]
<Response [401]> https://icsd.fiz-karlsruhe.de/ws/auth/login
Is there a solution?

**Comment by simonverret** [comment]
Wow, I sure took a long time to find my way here! Thanks for filling this issue. Simple bug indeed. I wrote a fix, but couldn't test it because I no longer have access to ICSD. Hopefully it doesn't bring other problems.
