### ISSUE TITLE
Response [401]

### ISSUE THREAD

**Issue by 279zlj** [simonverret/materials_data_api_scripts#2]
<Response [401]> https://icsd.fiz-karlsruhe.de/ws/auth/login
ConnectionError: {'Set-Cookie': 'ICSDCHECK=1627450974806; Path=/, JSESSIONID=725F1C650752434D5FE9692C5C71F60E; Path=/; HttpOnly, FIZ-Cookie=238830221.16671.0000; path=/; Httponly; Secure', 'Content-Type': 'text/plain', 'Content-Length': '98', 'Date': 'Wed, 28 Jul 2021 05:42:54 GMT', 'Keep-Alive': 'timeout=20', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=31536000 ; includeSubDomains'}
Is there a solution?

**Comment by simonverret** [comment]
I think this is normal if you do not have an ICSD License access. But I'm not certain.
